### ISSUE TITLE
Request for 2d blind deconvolution  example

### ISSUE THREAD

**Issue by murphyk** [vicariousinc/PGMax#112]
Can you share the code for the 2d blind deconvolution  example from your PMP paper (sec 5.6 of https://arxiv.org/pdf/2111.02458.pdf)

**Comment by lazarox** [comment]
I wrote that code prior to the release of this package, you can find it here :

https://github.com/vicariousinc/perturb_and_max_product/blob/master/experiments/exp6_convor.py

**Comment by antoine-dedieu** [comment]
@murphyk we have added this collab notebook to solve the 2d blind deconvolution example with PGMax
https://colab.research.google.com/drive/1w_ufQz0u18V_paM8pI97CO11965MduO4?usp=sharing
